#!/bin/bash
#!/bin/bash

year=$1
day=$2
lang=$3

base="https://adventofcode.com/${year}/day/${day}"

input=$(curl -s -b $(cat .session) "${base}/input")
if [ "$input" = "Puzzle inputs differ by user.  Please log in to get your puzzle input." ]; then
    echo "Invalid session cookie, please update"
    exit -1
fi

mkdir -p "${year}/${day}"
if [ "$lang" = "c" ]; then
    cp -ar "./templates/c/." "${year}/${day}"
else
    touch "${year}/${day}/$(echo day_${day}.${lang} | tr '[:upper:]' '[:lower:]')"
fi

curl -s -b $(cat .session) "${base}/input" -o "${year}/${day}/input.txt"
# curl -s -b $(cat .session) "${base}" -o "${year}/${day}/challange.html"
# sed -i "s/\/static/..\/..\/css/" "${year}/${day}/challange.html"


# open challange in firefox
powershell -Command "start firefox \"${base}\""
# open vscode in folder for current day
powershell -Command "code \"./${year}/${day}/\""
